import os
from datetime import datetime
from langchain_core.tools import tool
from langchain_anthropic import ChatAnthropic
from dotenv import load_dotenv

load_dotenv()

llm = ChatAnthropic(
    model="claude-haiku-4-5-20251001",
    api_key=os.getenv("ANTHROPIC_API_KEY"),
    max_tokens=2000
)


@tool
def analyze_competitor(brand: str, category: str) -> str:
    """
    Analyze a competitor brand in a category.
    Returns strengths, weaknesses, and positioning.
    """
    competitors = {
        ("boat", "headphones"): {
            "strengths":   ["Aggressive pricing", "Strong India brand", "High review volume", "Wide distribution"],
            "weaknesses":  ["Build quality concerns", "ANC quality below premium", "After-sales service"],
            "positioning": "Value-for-money leader in budget segment",
            "price_range": "Rs.500 - Rs.5000",
            "market_share": "32% (India budget segment)",
        },
        ("sony", "headphones"): {
            "strengths":   ["Best-in-class ANC", "Premium build quality", "Strong brand trust", "Innovation leader"],
            "weaknesses":  ["Premium pricing", "Limited budget options", "Less India-specific features"],
            "positioning": "Premium audio quality for audiophiles and professionals",
            "price_range": "Rs.3000 - Rs.30000",
            "market_share": "28% (India premium segment)",
        },
        ("jbl", "headphones"): {
            "strengths":   ["Brand recognition", "Good bass response", "Wide price range", "Durable build"],
            "weaknesses":  ["ANC quality mid-tier", "App experience", "Crowded mid-range positioning"],
            "positioning": "Mid-range performance with strong brand recall",
            "price_range": "Rs.1000 - Rs.15000",
            "market_share": "18% (India mid segment)",
        },
    }

    key = (brand.lower(), category.lower())
    if key not in competitors:
        return f"No data for {brand} in {category}. Available brands: boAt, Sony, JBL"

    c = competitors[key]
    return (
        f"COMPETITOR ANALYSIS — {brand.upper()}\n"
        f"Positioning: {c['positioning']}\n"
        f"Price Range: {c['price_range']}\n"
        f"Market Share: {c['market_share']}\n"
        f"Strengths: {', '.join(c['strengths'])}\n"
        f"Weaknesses: {', '.join(c['weaknesses'])}"
    )


@tool
def write_research_report(
    category: str,
    market_overview: str,
    competitor_analysis: str,
    opportunities: str
) -> str:
    """
    Write a professional market research report.
    Combines market overview, competitor analysis, and opportunities into a structured report.
    """
    date = datetime.now().strftime("%B %d, %Y")
    report = f"""
╔══════════════════════════════════════════════════════════╗
  MARKET RESEARCH REPORT
  Category: {category.upper()}
  Date: {date}
╚══════════════════════════════════════════════════════════╝

EXECUTIVE SUMMARY
{market_overview}

COMPETITIVE LANDSCAPE
{competitor_analysis}

MARKET OPPORTUNITIES
{opportunities}

RECOMMENDATION
Based on the analysis above, focus on the underserved segments
identified in the opportunities section for maximum ROI.
Entry strategy: target the gap between budget and mid-range
with superior product quality at competitive pricing.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Market Research Agent | 100 Days of AI/ML
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    return report.strip()