import os
from dotenv import load_dotenv
from langchain_anthropic import ChatAnthropic
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent

load_dotenv()

llm = ChatAnthropic(
    model="claude-haiku-4-5-20251001",
    api_key=os.getenv("ANTHROPIC_API_KEY"),
    max_tokens=800
)


# Research worker tools
@tool
def search_market_data(query: str) -> str:
    """Search for market data and statistics."""
    data = {
        "headphones market": "Rs.3200 crore, 22% CAGR, boAt leads budget",
        "earbuds market": "Rs.4800 crore, 35% CAGR, TWS dominates 80%",
        "laptop market": "Rs.18000 crore, 12% CAGR, Dell leads mid-range",
        "smartphone market": "Rs.150000 crore, 8% CAGR, Samsung leads volume",
    }
    for key in data:
        if any(word in query.lower() for word in key.split()):
            return data[key]
    return f"Market data for '{query}': Growing segment with 15% avg CAGR"


@tool
def get_competitor_info(brand: str) -> str:
    """Get competitor information for a brand."""
    brands = {
        "boat":    "boAt: Budget leader, 32% market share, aggressive pricing, weak ANC",
        "sony":    "Sony: Premium leader, 28% share, best ANC, high price point",
        "apple":   "Apple: Ecosystem play, 25% premium share, loyalty driven",
        "samsung": "Samsung: Multi-segment, strong distribution, mid-range focus",
    }
    return brands.get(brand.lower(), f"{brand}: Emerging player in the market")


# Writing worker tools
@tool
def write_section(title: str, content: str) -> str:
    """Write a formatted report section."""
    return f"\n## {title}\n{content}\n"


@tool
def format_report(sections: str) -> str:
    """Format the final report with header and footer."""
    return f"""
{'='*50}
MARKET RESEARCH REPORT
{'='*50}
{sections}
{'='*50}
Generated by Multi-Agent System
{'='*50}"""


# Create specialist agents
research_agent = create_react_agent(llm, [search_market_data, get_competitor_info])
writing_agent  = create_react_agent(llm, [write_section, format_report])


def run_research_agent(task: str) -> str:
    result = research_agent.invoke({"messages": [("human", task)]})
    return result["messages"][-1].content


def run_writing_agent(task: str) -> str:
    result = writing_agent.invoke({"messages": [("human", task)]})
    return result["messages"][-1].content